In [2]:
from pathlib import Path
import pandas as pd

In [3]:
DATA_ROOT = Path(
    "data/idx_financial_statements"
)

print(DATA_ROOT.resolve())
print("Exists:", DATA_ROOT.exists())

E:\BINUS_CODING\Ai Builders Hackhaton\AI-Builders-Hackhaton-2026-Backend\data\idx_financial_statements
Exists: True

In [4]:
folders = []

for path in DATA_ROOT.rglob("*"):

    if not path.is_dir():
        continue

    relative_path = path.relative_to(
        DATA_ROOT
    )

    folders.append({
        "folder_name": path.name,
        "relative_path": str(relative_path),
        "depth": len(relative_path.parts),
        "parent_folder": path.parent.name
    })

folder_df = pd.DataFrame(folders)

print(
    "Total folders:",
    len(folder_df)
)

display(
    folder_df.head(100)
)

Total folders: 31743

,folder_name,relative_path,depth,parent_folder
0,Financial_Statement_2020,Financial_Statement_2020,1,idx_financial_statements
1,Financial_Statement_2021,Financial_Statement_2021,1,idx_financial_statements
2,Financial_Statement_2022,Financial_Statement_2022,1,idx_financial_statements
3,Financial_Statement_2023,Financial_Statement_2023,1,idx_financial_statements
4,Financial_Statement_2024,Financial_Statement_2024,1,idx_financial_statements
...,...,...,...,...
95,BBRM,Financial_Statement_2020\BBRM,2,Financial_Statement_2020
96,BBSI,Financial_Statement_2020\BBSI,2,Financial_Statement_2020
97,BBSS,Financial_Statement_2020\BBSS,2,Financial_Statement_2020
98,BBTN,Financial_Statement_2020\BBTN,2,Financial_Statement_2020
99,BBYB,Financial_Statement_2020\BBYB,2,Financial_Statement_2020

In [5]:
for depth in sorted(
    folder_df["depth"].unique()
):

    print("\n" + "=" * 70)
    print("DEPTH:", depth)
    print("=" * 70)

    names = (
        folder_df[
            folder_df["depth"] == depth
        ]["folder_name"]
        .drop_duplicates()
        .head(100)
    )

    for name in names:
        print(name)

======================================================================
DEPTH: 1
======================================================================
Financial_Statement_2020
Financial_Statement_2021
Financial_Statement_2022
Financial_Statement_2023
Financial_Statement_2024
Financial_Statement_2025_Q2

======================================================================
DEPTH: 2
======================================================================
AALI
ABBA
ABDA
ABMM
ACES
ACST
ADCP
ADES
ADHI
ADMF
ADMG
ADMR
ADRO
AGAR
AGII
AGRO
AGRS
AHAP
AIMS
AISA
AKKU
AKPI
AKRA
AKSI
ALDO
ALKA
ALMI
ALTO
AMAG
AMAN
AMAR
AMFG
AMIN
AMMS
AMOR
AMRT
ANDI
ANJT
ANTM
APEX
APIC
APII
APLI
APLN
ARCI
ARGO
ARII
ARKA
ARKO
ARMY
ARNA
ARTA
ARTI
ARTO
ASBI
ASDM
ASGR
ASHA
ASII
ASJT
ASLC
ASMI
ASPI
ASRI
ASRM
ASSA
ATAP
ATIC
AUTO
AVIA
AXIO
AYLS
BABP
BACA
BAJA
BALI
BANK
BAPA
BAPI
BATA
BAUT
BAYU
BBCA
BBHI
BBKP
BBLD
BBMD
BBNI
BBRI
BBRM
BBSI
BBSS
BBTN
BBYB
BCAP
BCIC
BCIP
BDMN
BEBS
BEEF

======================================================================
DEPTH: 3
======================================================================
2025
2024
2023
2022
2021
2020

======================================================================
DEPTH: 4
======================================================================
Q1
Q2
Q3
Q4

In [8]:
COMPANY_DEPTH = 2

company_list = (
    folder_df[
        folder_df["depth"] == COMPANY_DEPTH
    ]["folder_name"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

company_df = pd.DataFrame({
    "ticker": company_list
})

print(
    "Total unique companies:",
    len(company_df)
)

display(company_df)

Total unique companies: 963

    ticker
0     AADI
1     AALI
2     ABBA
3     ABDA
4     ABMM
..     ...
958   ZATA
959   ZBRA
960   ZINC
961   ZONE
962   ZYRX

[963 rows x 1 columns]

In [9]:
print(
    company_df.to_string(
        index=False
    )
)

ticker
  AADI
  AALI
  ABBA
  ABDA
  ABMM
  ACES
  ACRO
  ACST
  ADCP
  ADES
  ADHI
  ADMF
  ADMG
  ADMR
  ADRO
  AEGS
  AGAR
  AGII
  AGRO
  AGRS
  AHAP
  AIMS
  AISA
  AKKU
  AKPI
  AKRA
  AKSI
  ALDO
  ALII
  ALKA
  ALMI
  ALTO
  AMAG
  AMAN
  AMAR
  AMFG
  AMIN
  AMMN
  AMMS
  AMOR
  AMRT
  ANDI
  ANJT
  ANTM
  APEX
  APIC
  APII
  APLI
  APLN
  ARCI
  AREA
  ARGO
  ARII
  ARKA
  ARKO
  ARMY
  ARNA
  ARTA
  ARTI
  ARTO
  ASBI
  ASDM
  ASGR
  ASHA
  ASII
  ASJT
  ASLC
  ASLI
  ASMI
  ASPI
  ASRI
  ASRM
  ASSA
  ATAP
  ATIC
  ATLA
  AUTO
  AVIA
  AWAN
  AXIO
  AYAM
  AYLS
  BABP
  BABY
  BACA
  BAIK
  BAJA
  BALI
  BANK
  BAPA
  BAPI
  BATA
  BATR
  BAUT
  BAYU
  BBCA
  BBHI
  BBKP
  BBLD
  BBMD
  BBNI
  BBRI
  BBRM
  BBSI
  BBSS
  BBTN
  BBYB
  BCAP
  BCIC
  BCIP
  BDKR
  BDMN
  BEBS
  BEEF
  BEER
  BEKS
  BELI
  BELL
  BESS
  BEST
  BFIN
  BGTG
  BHAT
  BHIT
  BIKA
  BIKE
  BIMA
  BINA
  BINO
  BIPI
  BIPP
  BIRD
  BISI
  BJBR
  BJTM
  BKDP
  BKSL
  BKSW
  BLES
  BLTA
  BLTZ
  BLUE
  BMAS
  BMBL
  BMHS
  BMRI
  BMSR
  BMTR
  BNBA
  BNBR
  BNGA
  BNII
  BNLI
  BOAT
  BOBA
  BOGA
  BOLA
  BOLT
  BOSS
  BPFI
  BPII
  BPTR
  BRAM
  BREN
  BRIS
  BRMS
  BRNA
  BRPT
  BRRC
  BSBK
  BSDE
  BSIM
  BSML
  BSSR
  BSWD
  BTEK
  BTEL
  BTON
  BTPN
  BTPS
  BUAH
  BUDI
  BUKA
  BUKK
  BULL
  BUMI
  BUVA
  BVIC
  BWPT
  BYAN
  CAKK
  CAMP
  CANI
  CARE
  CARS
  CASA
  CASH
  CASS
  CBDK
  CBMF
  CBPE
  CBRE
  CBUT
  CCSI
  CEKA
  CENT
  CFIN
  CGAS
  CHEM
  CHIP
  CINT
  CITA
  CITY
  CLAY
  CLEO
  CLPI
  CMNP
  CMNT
  CMPP
  CMRY
  CNKO
  CNMA
  CNTB
  CNTX
  COAL
  COCO
  COWL
  CPIN
  CPRI
  CPRO
  CRAB
  CRSN
  CSAP
  CSIS
  CSMI
  CSRA
  CTBN
  CTRA
  CTTH
  CUAN
  CYBR
  DAAZ
  DADA
  DART
  DATA
  DAYA
  DCII
  DEAL
  DEFI
  DEPO
  DEWA
  DEWI
  DFAM
  DGIK
  DGNS
  DGWG
  DIGI
  DILD
  DIVA
  DKFT
  DKHH
  DLTA
  DMAS
  DMMX
  DMND
  DNAR
  DNET
  DOID
  DOOH
  DOSS
  DPNS
  DPUM
  DRMA
  DSFI
  DSNG
  DSSA
  DUCK
  DUTI
  DVLA
  DWGL
  DYAN
  EAST
  ECII
  EDGE
  EKAD
  ELIT
  ELPI
  ELSA
  ELTY
  EMDE
  EMTK
  ENAK
  ENRG
  ENVY
  ENZO
  EPAC
  EPMT
  ERAA
  ERAL
  ERTX
  ESIP
  ESSA
  ESTA
  ESTI
  ETWA
  EURO
  EXCL
  FAPA
  FAST
  FASW
  FILM
  FIMP
  FIRE
  FISH
  FITT
  FLMC
  FMII
  FOLK
  FOOD
  FORE
  FORU
  FORZ
  FPNI
  FREN
  FUJI
  FUTR
  FWCT
  GAMA
  GDST
  GDYR
  GEMA
  GEMS
  GGRM
  GGRP
  GHON
  GIAA
  GJTL
  GLOB
  GLVA
  GMFI
  GMTD
  GOLD
  GOLF
  GOLL
  GOOD
  GOTO
 GOTOM
  GPRA
  GPSO
  GRIA
  GRPH
  GRPM
  GSMF
  GTBO
  GTRA
  GTSI
  GULA
  GUNA
  GWSA
  GZCO
  HADE
  HAIS
  HAJJ
  HALO
  HATM
  HBAT
  HDFA
  HDIT
  HDTX
  HEAL
  HELI
  HERO
  HEXA
  HGII
  HILL
  HITS
  HKMU
  HMSP
  HOKI
  HOME
  HOMI
  HOPE
  HOTL
  HRME
  HRTA
  HRUM
  HUMI
  HYGN
  IATA
  IBFN
  IBOS
  IBST
  ICBP
  ICON
  IDEA
  IDPR
  IFII
  IFSH
  IGAR
  IIKP
  IKAI
  IKAN
  IKBI
  IKPM
  IMAS
  IMJS
  IMPC
  INAF
  INAI
  INCF
  INCI
  INCO
  INDF
  INDO
  INDR
  INDS
  INDX
  INDY
  INET
  INKP
  INOV
  INPC
  INPP
  INPS
  INRU
  INTA
  INTD
  INTP
  IOTF
  IPAC
  IPCC
  IPCM
  IPOL
  IPPE
  IPTV
  IRRA
  IRSX
  ISAP
  ISAT
  ISEA
  ISSP
  ITIC
  ITMA
  ITMG
  JARR
  JAST
  JATI
  JAWA
  JAYA
  JECC
  JGLE
  JIHD
  JKON
  JKSW
  JMAS
  JPFA
  JRPT
  JSKY
  JSMR
  JSPT
  JTPE
  KAEF
  KAQI
  KARW
  KAYU
  KBAG
  KBLI
  KBLM
  KBLV
  KBRI
  KDSI
  KDTN
  KEEN
  KEJU
  KETR
  KIAS
  KICI
  KIJA
  KING
  KINO
  KIOS
  KJEN
  KKES
  KKGI
  KLAS
  KLBF
  KLIN
  KMDS
  KMTR
  KOBX
  KOCI
  KOIN
  KOKA
  KONI
  KOPI
  KOTA
  KPAL
  KPAS
  KPIG
  KRAH
  KRAS
  KREN
  KRYA
  KSIX
  KUAS
  LABA
  LABS
  LAJU
  LAND
  LAPD
  LCGP
  LCKM
  LEAD
  LFLO
  LIFE
  LINK
  LION
  LIVE
  LMAS
  LMAX
  LMPI
  LMSH
  LOPI
  LPCK
  LPGI
  LPIN
  LPKR
  LPLI
  LPPF
  LPPS
  LRNA
  LSIP
  LTLS
  LUCK
  LUCY
  MABA
  MAGP
  MAHA
  MAIN
  MAMI
 MAMIP
  MANG
  MAPA
  MAPB
  MAPI
  MARI
  MARK
  MASA
  MASB
  MAXI
  MAYA
  MBAP
  MBMA
  MBSS
  MBTO
  MCAS
  MCOL
  MCOR
  MDIA
  MDIY
  MDKA
  MDKI
  MDLA
  MDLN
  MDRN
  MEDC
  MEDS
  MEGA
  MEJA
  MENN
  MERK
  META
  MFIN
  MFMI
  MGLV
  MGNA
  MGRO
  MHKI
  MICE
  MIDI
  MIKA
  MINA
  MINE
  MIRA
  MITI
  MKAP
  MKNT
  MKPI
  MKTR
  MLBI
  MLIA
  MLPL
  MLPT
  MMIX
  MMLP
  MNCN
  MOLI
  MORA
  MPIX
  MPMX
  MPOW
  MPPA
  MPRO
  MPXL
  MRAT
  MREI
  MSIE
  MSIN
  MSJA
  MSKY
  MSTI
  MTDL
  MTEL
  MTFN
  MTLA
  MTMH
  MTPS
  MTRA
  MTSM
  MTWI
  MUTU
  MYOH
  MYOR
  MYRX
 MYRXP
  MYTX
  NAIK
  NANO
  NASA
  NASI
  NATO
  NAYZ
  NCKL
  NELY
  NEST
  NETV
  NFCX
  NICE
  NICK
  NICL
  NIKL
  NINE
  NIPS
  NIRO
  NISP
  NOBU
  NPGF
  NRCA
  NSSS
  NTBK
  NUSA
  NZIA
  OASA
  OBAT
  OBMD
  OCAP
  OILS
  OKAS
  OLIV
  OMED
  OMRE
  OPMS
  PACK
  PADA
  PADI
  PALM
  PAMG
  PANI
  PANR
  PANS
  PART
  PBID
  PBRX
  PBSA
  PCAR
  PDES
  PDPP
  PEGE
  PEHA
  PEVE
  PGAS
  PGEO
  PGJO
  PGLI
  PGUN
  PICO
  PIPA
  PJAA
  PKPK
  PLAN
  PLAS
  PLIN
  PMJS
  PMMP
  PNBN
  PNBS
  PNGO
  PNIN
  PNLF
  PNSE
  POLA
  POLI
  POLL
  POLU
  POLY
  POOL
  PORT
  POSA
  POWR
  PPGL
  PPRE
  PPRI
  PPRO
  PRAS
  PRAY
  PRDA
  PRIM
  PSAB
  PSDN
  PSGO
  PSKT
  PSSI
  PTBA
  PTDU
  PTIS
  PTMP
  PTMR
  PTPP
  PTPS
  PTPW
  PTRO
  PTSN
  PTSP
  PUDP
  PURA
  PURE
  PURI
  PWON
  PYFA
  PZZA
  RAAM
  RAFI
  RAJA
  RALS
  RANC
  RATU
  RBMS
  RCCC
  RDTX
  REAL
  RELF
  RELI
  RGAS
  RICY
  RIGS
  RIMO
  RISE
  RMBA
  RMKE
  RMKO
  ROCK
  RODA
  RONY
  ROTI
  RSCH
  RSGK
  RUIS
  RUNS
  SAFE
  SAGE
  SAME
  SAMF
  SAPX
  SATU
  SBAT
  SBMA
  SCCO
  SCMA
  SCNP
  SCPI
  SDMU
  SDPC
  SDRA
  SEMA
  SFAN
  SGER
  SGRO
  SHID
  SHIP
  SICO
  SIDO
  SILO
  SIMA
  SIMP
  SINI
  SIPD
  SKBM
  SKLT
  SKRN
  SKYB
  SLIS
  SMAR
  SMBR
  SMCB
  SMDM
  SMDR
  SMGA
  SMGR
  SMIL
  SMKL
  SMKM
  SMLE
  SMMA
  SMMT
  SMRA
  SMRU
  SMSM
  SNLK
  SOCI
  SOFA
  SOHO
  SOLA
  SONA
  SOSS
  SOTS
  SOUL
  SPMA
  SPRE
  SPTO
  SQMI
  SRAJ
  SRIL
  SRSN
  SRTG
  SSIA
  SSMS
  SSTM
  STAA
  STAR
  STRK
  STTP
  SUGI
  SULI
  SUNI
  SUPR
  SURE
  SURI
  SWAT
  SWID
  TALF
  TAMA
  TAMU
  TAPG
  TARA
  TAXI
  TAYS
  TBIG
  TBLA
  TBMS
  TCID
  TCPI
  TDPM
  TEBE
  TECH
  TELE
  TFAS
  TFCO
  TGKA
  TGRA
  TGUK
  TIFA
  TINS
  TIRA
  TIRT
  TKIM
  TLDN
  TLKM
  TMAS
  TMPO
  TNCA
  TOBA
  TOOL
  TOPS
  TOSK
  TOTL
  TOTO
  TOWR
  TOYS
  TPIA
  TPMA
  TRAM
  TRGU
  TRIL
  TRIM
  TRIN
  TRIO
  TRIS
  TRJA
  TRON
  TRST
  TRUE
  TRUK
  TRUS
  TSPC
  TUGU
  TURI
  TYRE
  UANG
  UCID
  UDNG
  UFOE
  ULTJ
  UNIC
  UNIQ
  UNIT
  UNSP
  UNTD
  UNTR
  UNVR
  URBN
  UVCR
  VAST
  VERN
  VICI
  VICO
  VINS
  VISI
  VIVA
  VKTR
  VOKS
  VRNA
  VTNY
  WAPO
  WEGE
  WEHA
  WGSH
  WICO
  WIDI
  WIFI
  WIIM
  WIKA
  WINE
  WINR
  WINS
  WIRG
  WMPP
  WMUU
  WOMF
  WOOD
  WOWS
  WSBP
  WSKT
  WTON
  YELO
  YOII
  YPAS
  YULE
  YUPI
  ZATA
  ZBRA
  ZINC
  ZONE
  ZYRX